### ISSUE TITLE
[WORD] ERROR 官方文档有一个字错了

### ISSUE THREAD

**Issue by ShenQingchuan** [vlang-cc/vlang-cc#1]
## Where is it ？错误在哪儿
https://vlang-cc.github.io/office/vlang.html#%E6%80%A7%E8%83%BD%E6%98%AF%E4%B8%8D%E6%98%AF%E5%BE%88%E7%83%82%EF%BC%9F

目前V生成C代码，然后通过GCC和Clang来进行优化。通过这种方式可以使用复杂的优化技术。

不过这种方式构建的速度比V编译要慢150被（但是依然比C++的编译速度快一个数量级）。

## How to Fix ？如何修复？
**要慢150被** 应改为 **要慢150倍**

**Comment by ShenQingchuan** [comment]
## ERROR 2：
V语言可以输出C代码，因此 **只有有 **C语言的地方都可以用V语言开发应用，同时可以借助GCC或Clang强大的优化能力。V语言可以没有代价地调用C函数，同时其它任何语言也可以像调用C函数那样调用V语言函数

## How to Fix ？ 如何修复？
**只有有** 应改为 **只要有**

**Comment by krircc** [comment]
@ShenQingchuan Thank you . I fix now
